development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: <%= ENV["DEV_DB_NAME"] %>
  pool: 5
  username: <%= ENV["DEV_DB_USERNAME"] %>
  password: <%= ENV["DEV_DB_PASSWORD"] %>

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: <%= ENV["TEST_DB_NAME"] %>
  pool: 5
  username: <%= ENV["TEST_DB_USERNAME"] %>
  password: <%= ENV["TEST_DB_PASSWORD"] %>

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: <%= ENV["PROD_DB_NAME"] %>
  pool: 5
  username: <%= ENV["PROD_DB_USERNAME"] %>
  password: <%= ENV["PROD_DB_PASSWORD"] %>